### ISSUE TITLE
Questions about performance metric d4rl_score.

### ISSUE THREAD

**Issue by TianQi-777** [sfujim/TD3_BC#1]
I run the code in **halfcheetah-expert-v0**, and it seems to work well, but its performance metric **d4rl_score** is only about 1.1-1.2, and the result of the paper is about 110-120, I am confused. (my mujoco version is 200)

**Comment by sfujim** [comment]
The D4RL output is scaled from 0-1, while the paper reports 0-100, so you just need to multiply by 100. I need to adjust the code to reflect this though, because you're not the first person to ask this!

**Comment by TianQi-777** [comment]
Thanks for the prompt reply.
