### ISSUE TITLE
The results in Antmaze

### ISSUE THREAD

**Issue by lucasliunju** [sfujim/TD3_BC#2]
Hi,

I would like to ask the setting about the experiments in Antmaze. Should I need to tune the hyparameters for mujoco locomotion?

I find I cannot reproduce the results about Antmaze in the paper.

Best

**Comment by sfujim** [comment]
I believe the only difference from the default hyperparameters for Antmaze was that normalization was not used. You should be able to obtain even better results than what was reported in the paper by using larger values of alpha.
